### PR TITLE
Add a convenience script for the app on Linux and MacOS

### PR DESCRIPTION
**Pull request by ksandom**
* Grabs the latest code, and puts it into your clipboard.
* Starts slack with `SLACK_DEVELOPER_MENU=true`.
* At that point, all you have to do is the 
  * Right click.
  * Inspect.
  * Click console.
  * CTRL/CMD + v enter
  * Close

Still way more steps than it should be. But another step forward.

### CODE REVIEW

**Comment by rogerluan** [comment]
Awesome! Thanks!

**Comment by rogerluan** [comment]
I just had to change the last line to
```
SLACK_DEVELOPER_MENU=true /Applications/Slack.app/Contents/MacOS/Slack
```
Because on my Mac: `line 18: slack: command not found`

**Comment by ksandom** [comment]
@rogerluan Could you please give it another go? I've just added a basic check to select the right binary.

**Comment by ksandom** [comment]
Given that a much more convenient script based on patching is now [available](https://github.com/kfahy/slack-disable-wysiwyg-bookmarklet/blob/master/bin/patch-desktop-app). I'm going to close this. But feel free to re-open it if you'd like to have this available as well.

I'm still personally using this one, because I didn't want to risk wasting time cleaning up after a patch once the WYSIWYG editor officially becomes available again.

In either case, thanks for all your effort on this. It really has made things much more pleasant in the mean time.

**Comment by rogerluan** [comment]
Sorry I forgot to reply here that your last updates work for me :)

**Pull request closed without merging**
